name: My First Workflow

on:
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Date
        run: date

      - name: Print Current Directory
        run: pwd

      - name: List Files
        run: ls -la